#!/usr/bin/env bash

########################
# Author: Limony
# Date: 2023-01-01
###########################

unset github_username dir repo license_url

formula_name="fluffy-service-pack"
version="0.0.19"
script_name=$(basename "$0")
bin_dir=$(dirname "$0")
dir=$bin_dir"/../Cellar/"$formula_name"/"$version"/bin"
audio_dir=$dir"/audio"
sound_command=""
blocking=false

update_audio_dir(){
    if [ "$FSP_AUDIO_PATH" ]; then
        audio_dir=$FSP_AUDIO_PATH
    fi
}

check_audio_dir(){
    if [[ ! -d "$audio_dir" ]]; then
        echo "audio dir does not exist! Please reinstall or update audio dir path with:"
        echo "export FSP_AUDIO_PATH=<audio_dir_path>"
    fi
}

upgrade_version(){
    echo "Upgrading $formula_name..."
    brew upgrade $formula_name
}

help() {
    cat <<EOF
This service pack will help you relax with some fulffy sounds.

usage: $script_name <sound_name> [ -h | --help | -v | --version | -u | --upgrade | -b | --blocking]

Examples:
    $script_name so
    $script_name so_fluffy

Options:
so                                 - "so!"
so_fluffy                          - "so fluffy!"
fluffy | fluffy!                   - "fluffy!"
its_so_fluffy | isf                - "its so fluffy!"
its_so_fluffy_im_gonna_die | sfigd - "its so fluffy im gonna die!"
always_could_count_on_you | accoy  - "always could count on you!"
oooweee | oowee | owe              - "oooweee!"
hihi | hh | worms                  - "hi hi hi hi" (high pitch worm)
plumbus | pb | p                   - "plumbus"
always_wondered | aw | plumbuses   - "I always wondered how Plumbuses got made"
come_back | cb || cbs || cbst | c  - "come back"
raccoon || puree || papaya         - "?"
papoi || papoi2                    - "papoi"
t1 || t2 || t3                     - "i want to be there"
here | i_am_here                   - "i am here"
not_here | nh                      - "i dont want to be here"
still_here | sh                    - "still here?"
good | goody | g                   - "goody"
matan                              - "Matan isn't it Purim today?"
what_do_you_want | wdyw            - "what do you want?!"
crickets | crcr                    - "crr crr"
lebowski | money                   - "where is the money lebowski"
get_to_the_choppa | gttc | choppa  - "get to the choppa!"
arm_the_laser | laser | "laser"    - "arm the laser!"
floccinaucinihilipilification|floc - "floccinaucinihilipilification" 
ding_dong | ding | d               - [doorbell]
hello | h                          - "hello!"
free_book | fb                     - "I have a free book"
spider_pig | sp                    - "spider pig, spider pig"
ba_dum_tss | bdt | drums           - [drums sound]
seinfeld | seinfeld_theme          - [seinfeld theme]
kube                               - "Kube Hamusta"
lemon | give_me_lemons             - [ascii lemon!]
bean | give_me_beans               - [ascii mr bean!]

EOF
}

# General #
control_options(){
    case "$1" in
        -h | --help)
        help
        exit
        ;;
        -v | --version)
        echo ${version}
        exit
        ;;
        -d | --dir)
        echo bin_dir=$bin_dir
        echo dir=$dir
        echo audio_dir=$audio_dir
        exit
        ;;
        -u | --upgrade)
        upgrade_version
        exit
        ;;
        "")
        echo No operation provided!
        echo
        help
        exit
        ;;
    esac

    sound_command=$1
}

# Sound functions #
sound_options(){
    case "$1" in
        -b | --blocking)
        blocking=true
        ;;
    esac

    if [ "$blocking" = true ]; 
    then
        finish_sound="&& exit"
    else
        finish_sound="& exit"
    fi
}

play(){
    eval afplay $1 $finish_sound
}

# Ascii functions #
give_me_lemon() {
    cat <<EOF
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⠉⠁⠀⠀⠀⠀⠈⠙⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠛⠙⢻⣿⣿⡿⠋⠌⠀⠐⠀⠀⠄⠀⠀⠀⠀⠀⠀⠉⠛⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣤⠀⠙⠑⡀⢁⠀⢄⠠⡀⡄⡄⡄⣂⡡⣀⣂⣀⢀⣠⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⠉⢄⠊⢰⡳⣽⣺⢽⡽⡽⣕⣧⡳⣕⣕⣎⡖⣜⢌⢎⡪⡪⢹⠹⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⠟⠋⠀⠀⢌⠢⠨⢐⢝⡾⣽⢯⣟⣯⡿⣾⡽⣷⢷⣗⣯⣷⣫⢧⡣⣇⢇⢇⢇⠪⡫⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⡿⠏⠁⠀⠀⠀⠌⢜⠌⡂⠌⡮⣻⣽⢿⡽⡷⣟⣯⣿⣻⡿⣽⢷⣻⡾⣯⢟⣮⣳⢵⡱⡱⡑⡌⢏⢿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⡟⠁⠀⠂⠀⠁⠠⡁⢇⠅⡂⠨⢪⢳⢯⣿⣻⣟⣿⡽⣯⣷⢿⣻⢿⡽⣯⣯⢿⣺⢾⢵⣝⢮⢪⢪⢊⠜⡽⣿⣿⣿⣿⣿⣿
⣿⣿⠏⠀⠀⠐⠀⠐⠀⠌⠄⢕⠐⠀⠌⢪⢹⢽⣺⣳⣟⡾⣯⢷⣻⣯⢿⡯⣿⣳⡿⣽⢯⢿⢽⣪⢗⡽⡸⡰⡑⡸⠸⣿⣿⣿⣿⣿
⣿⡟⠀⡀⠁⠀⠂⠀⠂⠅⡘⠔⠈⡀⠌⠸⡸⣝⣞⣗⡯⣯⢯⢿⢽⣞⣯⢿⡽⣞⣯⢿⢽⢯⣟⢾⢝⡮⣳⢱⠱⡘⢌⢎⢿⣿⣿⣿
⣿⡇⠀⠀⡀⠈⠀⠐⠨⠐⠨⠈⢀⠀⢂⢑⠕⣕⢵⡳⣫⣗⡯⣟⣽⣺⢽⢽⡽⣽⣺⢽⢽⣝⡮⡯⣳⢝⡎⡮⡪⡊⢆⠪⡪⣿⣿⣿
⣿⡇⠀⢀⠀⠠⠈⢀⠁⠨⢈⠠⠀⠐⡀⠢⡱⡱⡱⣝⢞⡼⣪⢗⢧⣳⡫⣗⡽⣺⡪⡯⣳⢳⢝⢮⡳⣣⢫⡪⡪⡪⡂⡣⢊⢺⣿⣿
⣿⣇⠀⠀⢀⠀⠄⠠⠀⡁⠄⠀⠠⠁⠄⡑⢔⠱⡱⡱⡳⣹⢪⣫⢳⠵⡝⡮⡺⣕⢽⡹⣪⡫⡳⣣⡫⡪⡣⡣⡣⡣⢪⠨⠢⡱⣻⣿
⣿⣿⡄⠀⡀⠀⠠⠀⠂⢀⠀⠄⡡⢈⢐⠠⢡⢑⠕⡕⡕⡕⡧⡳⡹⡹⣜⢵⡹⡜⡎⣞⢜⢮⢹⢢⢳⢹⢸⢸⠸⡘⢔⠡⡑⢜⢺⣿
⣿⣿⣷⡀⠀⠠⠐⠀⢁⠀⡀⡢⢂⠂⡐⠨⢐⠡⡱⡘⡌⡎⡎⡎⡇⣏⢮⢪⢎⢮⢺⢸⢸⢸⢸⢸⠸⡘⡌⢆⢣⢑⠅⢕⠨⢂⣻⣿
⣿⣿⣿⣷⠈⠀⠐⠈⡀⣴⠨⢂⠂⡂⢂⠡⠂⢕⢐⢑⢌⠆⡇⡣⡣⡣⡣⡣⡣⡣⡣⢣⠣⡃⡇⢕⢑⠕⡘⢌⠢⡡⠡⡡⢊⢐⢾⣿
⣿⣿⣿⣿⡇⢀⢁⣦⣿⣿⣧⢁⢂⢂⠂⠌⢌⠐⢌⠢⢡⠱⡨⢊⢆⢣⠪⡊⢆⢣⢊⢪⢘⠌⡌⡪⢐⠅⢅⠅⠕⡐⠡⢂⢂⢢⣿⣿
⣿⣿⣿⣿⣿⣠⣾⣿⣿⣿⣿⣮⡐⠄⢅⢑⠠⠑⠄⢅⢑⠌⠢⡑⢔⢡⠱⡘⢌⠢⡑⢔⠡⡊⠔⡈⡂⠅⠅⠌⡂⠌⢌⢐⢐⢸⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣕⢐⢐⠨⠨⠨⢐⢐⠨⠨⠂⢅⠢⠑⠌⠢⡑⠌⡂⠅⡂⡑⡐⠨⠈⠌⡐⠠⢁⢂⢂⢂⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣮⣢⢈⠂⠅⡂⠂⠌⠌⠨⢐⠨⠨⢈⢂⠂⠅⢂⢁⢂⢐⠠⠁⠅⠡⠀⠅⢂⢐⠠⣾⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣬⡂⡂⠅⠡⠈⠌⡀⢂⠁⡂⠐⢈⠐⢀⠂⠠⠀⠂⡁⠈⠄⠁⠌⠠⢐⣼⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣥⡅⡅⠡⠐⡀⢂⠠⠈⡀⠐⡀⠄⢁⠈⠠⠐⠈⡀⠡⠈⢄⣳⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣷⣴⣔⣄⣅⡄⡅⡄⣂⢔⡨⣐⣌⣔⣤⣥⣱⣼⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
EOF
}

give_me_bean() {
    cat <<EOF
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⣤⣶⣶⣶⣶⣶⣶⣶⣤⣤⣤⣤⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣴⡶⠟⠛⠉⠛⠛⠉⠙⠿⢛⣫⣽⣿⣿⣿⣿⣿⣿⣷⣦⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣶⡿⠛⠉⠀⠀⢀⠀⠀⠀⠀⢀⣾⣿⠿⢛⣭⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⣁⣤⡶⠂⣠⣴⠏⠀⠀⠤⠾⠟⠋⢁⣀⣛⣛⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣤⡀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⢠⣾⣿⣿⣿⣿⣿⣿⣟⣭⡞⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡦⢹⣦⡀⠀⠀⠀⠀
⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠉⣽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⣿⣿⣷⡄⠀⠀⠀
⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣀⠀⠀⠀⠀⠀⠀⠀⢘⣿⣿⣿⣿⣿⡿⠿⠿⠿⠿⣿⣿⢟⣿⣿⣿⣿⠀⠀⠀
⠀⠀⢠⣿⣿⣿⣿⣿⢿⣿⡿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣶⣶⣶⣾⠿⠿⠛⠛⠉⠁⠀⠀⠀⠀⠀⠀⠈⣻⣦⣿⣿⣿⣿⡆⠀⠀
⠀⠀⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⣿⣿⣿⣿⣿⣷⠀⠀
⠀⠀⣿⣿⣿⣿⣿⠀⠀⠀⢀⣄⣀⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠐⠒⠒⠂⠀⣀⣀⣀⣀⣀⠀⠀⠘⣿⣿⣿⣿⣿⣿⠀⠀
⠀⠀⣿⣿⣿⣿⠇⠀⠀⣠⠤⢤⣤⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⠤⠴⠒⠛⢉⣉⡥⠤⠶⠬⣽⡢⠀⡘⣿⣿⣿⣿⣿⠀⠀
⠀⠀⣿⣿⣿⣿⠀⠀⠀⣠⡶⠶⠶⠤⣍⡙⠓⠶⢤⣄⣀⡀⠀⠀⠀⢀⣀⡤⠶⠚⢉⡤⠖⠋⢉⠓⠢⠙⠂⠸⣿⣿⣿⣿⡏⠀⠀
⢀⣀⣸⣿⣿⣿⠀⠀⠀⣥⣾⣷⣦⣄⡀⠉⠓⠲⢤⣀⠈⠉⠉⠉⠉⠉⠀⠀⠀⠀⢀⣠⣴⣾⣿⣿⣶⣄⠀⠀⢻⣿⣿⣿⣷⡦⡀
⢻⣧⡉⢿⣿⡏⠀⠀⣼⠟⠉⠙⠛⠿⣿⣷⣦⡀⠀⠈⠑⠀⠀⠀⠀⠀⠀⠀⣠⣶⣿⠿⠛⠉⠈⠉⠉⠻⡄⠀⠘⣿⣿⡿⢿⣷⡷
⠘⣿⡇⠸⣿⡇⠀⢠⡏⠀⠀⣠⠴⢶⣦⣌⡙⠻⢷⣄⠀⣀⣀⡀⣀⡬⣦⠾⠋⢁⣠⣶⣚⣻⣓⠲⣄⠀⠱⠀⠀⣿⣿⠖⢠⣿⠃
⠀⠘⣿⠀⣿⡇⠀⠈⠀⢀⣘⣿⠋⣽⣿⣿⠻⣶⣄⠈⢧⡀⠀⠀⠁⢀⣿⠀⣴⡿⢋⣿⣸⣶⠉⣷⣬⡀⠀⠀⠀⢿⡟⠀⣴⠁⠀
⠀⠀⠸⡇⠘⠃⠀⠀⠀⠀⡛⢯⣀⠻⠿⢟⣀⣾⠿⠂⠞⢳⡀⠀⠀⣿⣟⠈⠛⠃⣄⣛⣛⣋⣠⠵⢋⠀⠀⠀⠀⠀⣧⢸⡇⠀⠀
⠀⠀⠀⣷⠴⡇⠀⠀⣠⠴⠿⣷⣾⣷⣿⣛⣉⠁⠀⠀⠀⢸⡆⠀⠀⠈⠀⠀⠀⠀⠻⢶⣶⣶⡶⠶⠯⠝⠀⠀⠀⢰⠙⣾⠀⠀⠀
⠀⠀⠀⣧⠀⠑⠀⣸⠁⠀⠀⠀⠀⠀⠀⠉⠁⠀⢀⣀⠀⣼⡧⠀⠀⠀⠀⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⡟⢁⡏⠀⠀⠀
⠀⠀⠀⠻⣆⣀⣴⡏⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⠏⠉⠙⠏⠀⠀⠀⠀⠀⠛⠈⢹⣷⣄⠀⠀⠀⠀⠀⠓⠀⠀⢸⣧⠜⠁⠀⠀⠀
⠀⠀⠀⠀⠈⠉⢸⣇⠀⠀⠀⠀⠀⠀⢠⡾⠟⠙⢆⡀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣼⠛⠛⠷⣄⡀⠀⠀⠀⠀⠀⣾⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢸⣿⡇⠀⢀⠀⠀⢰⣏⠀⠀⠀⠀⠉⠛⠳⢦⣀⠀⢀⡴⠛⠋⠀⠀⠀⠀⠀⠉⠢⡀⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢸⢻⡇⠀⢸⡇⠀⠀⠹⢤⣄⣀⠀⠀⠀⠀⠀⠙⠟⠋⠀⠀⠀⣀⡤⠖⠛⠳⠀⠀⠉⣲⠀⢸⠇⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢸⡌⢷⡀⠀⢿⡄⠀⠀⠀⠀⢯⡛⢶⡲⠦⠤⠤⡤⠤⠴⠒⢋⡅⠀⠀⠀⠀⠀⠀⢠⠏⢠⡟⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠘⣧⠀⠻⣦⡀⠻⣶⡄⠀⠀⠀⠙⠦⣤⣄⣀⣀⣀⣠⡤⠾⠋⠀⠀⠀⠀⠀⠀⣠⠏⡰⠋⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠙⣧⡀⠈⠻⣦⡈⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⠷⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠈⠛⢷⣦⣜⣿⣿⣿⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣾⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠿⢿⣿⣿⣿⣦⣤⣤⣀⣀⣀⣀⣀⣠⣤⣴⣾⡿⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠙⠛⠛⠛⠻⠿⠿⠿⠛⠛⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
EOF
}

############# Main body ############
main_options(){
    case "$1" in
        so)
            play "$audio_dir/so_audio.mp3"
        ;;

        so_fluffy)
            echo ">'so_fluffy!'"
            play "$audio_dir/so_fluffy_audio.wav"
        ;;

        fluffy | fluffy!)
            play "$audio_dir/fluffy_short.wav"
        ;;

        its_so_fluffy | isf)
            play "-v 4 $audio_dir/its_so_fluffy.mp3"
        ;;

        its_so_fluffy_im_gonna_die | so_fluffy_im_gonna_die | sfigd | isfigd | die)
            play "-v 4 $audio_dir/so_fluffy_im_gonna_die.mp3"
        ;;

        always_can_count_on_you | always_could_count_on_you | accoy)
            play "-v 7 $audio_dir/always_could_count_on_you.mp3"
        ;;

        owe | oowee | oooweee)
            play "-v 3 $audio_dir/oooweee.mp3"
        ;;
        
        hihi | worms | hh)
            play "$audio_dir/hihi_worms.mp3"
        ;;

        plumbus | pb | p)
            play "-v 2 $audio_dir/plumbus.mp3"
        ;;

        always_wondered | awhpgm | aw | plumbuses)
            play "$audio_dir/always_wondered.mp3"
        ;;

        come_back | cb)
            play "$audio_dir/come_back.mp3"
        ;;

        come_back_slow | cbs)
            play "$audio_dir/come_back_slow.mp3"
        ;;

        come_back_strong | cbst | c)
            play "$audio_dir/come_back_strong.mp3"
        ;;

        raccoon | r)
            play "$audio_dir/raccoon.mp3"
        ;;

        blintzes)
            play "$audio_dir/blintzes.mp3"
        ;;

        puree)
            play "$audio_dir/puree.mp3"
        ;;

        rummikub | remi | rumi)
            play "$audio_dir/rummikub.mp3"
        ;;

        papaya | pa)
            play "$audio_dir/papaya.mp3"
        ;;

        papoi)
            play "$audio_dir/papoi.mp3"
        ;;

        papoi2)
            play "$audio_dir/papoi2.mp3"
        ;;

        i_want_to_be_there_yes | iwtbt | there | t1)
            play "$audio_dir/i_want_to_be_there_yes.mp3"
        ;;

        i_want_to_be_there | there2 | t2)
            play "$audio_dir/i_want_to_be_theree.mp3"
        ;;

        there3 | t3)
            play "$audio_dir/i_want_to_be_there.mp3"
        ;;

        i_am_here | here | iah)
            play "$audio_dir/i_am_here.mp3"
        ;;

        dont_want_to_be_here | here_not | not_here | nh | dwtbh | idwtbh)
            play "$audio_dir/dont_want_to_be_here.mp3"
        ;;

        still_here | sh)
            play "$audio_dir/still_here.mp3"
        ;;

        goody | good | g)
            play "$audio_dir/goody.mp3"
        ;;

        where_is_the_money_lebowski | where_is_the_money | lebowski | money)
            play "$audio_dir/where_is_the_money_lebowski.mp3"
        ;;

        get_to_the_choppa | gttc | choppa)
            play "$audio_dir/get_to_the_choppa.mp3"
        ;;

        arm_the_laser | laser | atl)
            play "$audio_dir/arm_the_laser.mp3"
        ;;

        team_that_i_build | team)
            play "$audio_dir/team_builder.mp3"
        ;;

        miluim)
            play "$audio_dir/miluim.mp3"
        ;;

        matan | purim)
            play "-v 0.3 $audio_dir/matan.mp3"
        ;;

        what_do_you_want | wdyw)
            play "-v 0.3 $audio_dir/what_do_you_want.mp3"
        ;;

        story)
            play "-v 0.5 $audio_dir/story.mp3"
        ;;

        crickets | crcr)
            play "$audio_dir/crickets.mp3"
        ;;

        floccinaucinihilipilification | floc)
            play "$audio_dir/floccinaucinihilipilification.mp3"
        ;;

        ding_dong | ding | d)
            play "$audio_dir/ding_dong.mp3"
        ;;

        hello | h)
            play "$audio_dir/hello.mp3"
        ;;

        free_book | fb)
            play "$audio_dir/free_book.mp3"
        ;;

        spider_pig | sp)
            play "$audio_dir/spider_pig.mp3"
        ;;

        ba_dum_tss | bdt | drums)
            play "$audio_dir/ba_dum_tss.mp3"
        ;;

        seinfeld | seinfeld_theme)
            play $audio_dir/seinfeld_theme.mp3
        ;;

        kube)
            play $audio_dir/kube.mp3
        ;;

        lemon | give_me_lemons | give_me_lemon)
            give_me_lemon
            exit
        ;;

        bean | give_me_beans | give_me_bean)
            give_me_bean
            exit
        ;;

        *)
            echo No valid operation provided!
    esac
}


update_audio_dir
check_audio_dir
control_options $1
sound_options $2
main_options $sound_command
