name: Create tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag number'     
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ inputs.tag }}
          message: "version ${{ inputs.tag }}"
      - name: get release sha256
        run: |
          curl -L https://github.com/limonyellow/fluffy-service-pack/archive/refs/tags/v${{ inputs.tag }} --output release.tar.gz
          sha256sum release.tar.gz | cut -d " " -f1
        id: sha256
